/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SumOfRanksRouteImport } from './routes/sum-of-ranks'
import { Route as RecordStreakRouteImport } from './routes/record-streak'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as PersonsRouteImport } from './routes/persons'
import { Route as NameRanksRouteImport } from './routes/name-ranks'
import { Route as KinchRanksRouteImport } from './routes/kinch-ranks'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsAlgSetRouteImport } from './routes/algorithms/$algSet'

const SumOfRanksRoute = SumOfRanksRouteImport.update({
  id: '/sum-of-ranks',
  path: '/sum-of-ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordStreakRoute = RecordStreakRouteImport.update({
  id: '/record-streak',
  path: '/record-streak',
  getParentRoute: () => rootRouteImport,
} as any)
const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsRoute = PersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRanksRoute = NameRanksRouteImport.update({
  id: '/name-ranks',
  path: '/name-ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const KinchRanksRoute = KinchRanksRouteImport.update({
  id: '/kinch-ranks',
  path: '/kinch-ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsAlgSetRoute = AlgorithmsAlgSetRouteImport.update({
  id: '/algorithms/$algSet',
  path: '/algorithms/$algSet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/feedback': typeof FeedbackRoute
  '/kinch-ranks': typeof KinchRanksRoute
  '/name-ranks': typeof NameRanksRoute
  '/persons': typeof PersonsRoute
  '/ranks': typeof RanksRoute
  '/record-streak': typeof RecordStreakRoute
  '/sum-of-ranks': typeof SumOfRanksRoute
  '/algorithms/$algSet': typeof AlgorithmsAlgSetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/feedback': typeof FeedbackRoute
  '/kinch-ranks': typeof KinchRanksRoute
  '/name-ranks': typeof NameRanksRoute
  '/persons': typeof PersonsRoute
  '/ranks': typeof RanksRoute
  '/record-streak': typeof RecordStreakRoute
  '/sum-of-ranks': typeof SumOfRanksRoute
  '/algorithms/$algSet': typeof AlgorithmsAlgSetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/feedback': typeof FeedbackRoute
  '/kinch-ranks': typeof KinchRanksRoute
  '/name-ranks': typeof NameRanksRoute
  '/persons': typeof PersonsRoute
  '/ranks': typeof RanksRoute
  '/record-streak': typeof RecordStreakRoute
  '/sum-of-ranks': typeof SumOfRanksRoute
  '/algorithms/$algSet': typeof AlgorithmsAlgSetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions'
    | '/feedback'
    | '/kinch-ranks'
    | '/name-ranks'
    | '/persons'
    | '/ranks'
    | '/record-streak'
    | '/sum-of-ranks'
    | '/algorithms/$algSet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitions'
    | '/feedback'
    | '/kinch-ranks'
    | '/name-ranks'
    | '/persons'
    | '/ranks'
    | '/record-streak'
    | '/sum-of-ranks'
    | '/algorithms/$algSet'
  id:
    | '__root__'
    | '/'
    | '/competitions'
    | '/feedback'
    | '/kinch-ranks'
    | '/name-ranks'
    | '/persons'
    | '/ranks'
    | '/record-streak'
    | '/sum-of-ranks'
    | '/algorithms/$algSet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsRoute: typeof CompetitionsRoute
  FeedbackRoute: typeof FeedbackRoute
  KinchRanksRoute: typeof KinchRanksRoute
  NameRanksRoute: typeof NameRanksRoute
  PersonsRoute: typeof PersonsRoute
  RanksRoute: typeof RanksRoute
  RecordStreakRoute: typeof RecordStreakRoute
  SumOfRanksRoute: typeof SumOfRanksRoute
  AlgorithmsAlgSetRoute: typeof AlgorithmsAlgSetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sum-of-ranks': {
      id: '/sum-of-ranks'
      path: '/sum-of-ranks'
      fullPath: '/sum-of-ranks'
      preLoaderRoute: typeof SumOfRanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record-streak': {
      id: '/record-streak'
      path: '/record-streak'
      fullPath: '/record-streak'
      preLoaderRoute: typeof RecordStreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons': {
      id: '/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-ranks': {
      id: '/name-ranks'
      path: '/name-ranks'
      fullPath: '/name-ranks'
      preLoaderRoute: typeof NameRanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinch-ranks': {
      id: '/kinch-ranks'
      path: '/kinch-ranks'
      fullPath: '/kinch-ranks'
      preLoaderRoute: typeof KinchRanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$algSet': {
      id: '/algorithms/$algSet'
      path: '/algorithms/$algSet'
      fullPath: '/algorithms/$algSet'
      preLoaderRoute: typeof AlgorithmsAlgSetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRoute,
  FeedbackRoute: FeedbackRoute,
  KinchRanksRoute: KinchRanksRoute,
  NameRanksRoute: NameRanksRoute,
  PersonsRoute: PersonsRoute,
  RanksRoute: RanksRoute,
  RecordStreakRoute: RecordStreakRoute,
  SumOfRanksRoute: SumOfRanksRoute,
  AlgorithmsAlgSetRoute: AlgorithmsAlgSetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
